--                               LABORATORUL 8 - JAVA  - WORKING WITH DATABASE 
--- SIMPLE TEST: 
---  SELECT 1 FROM DUAL; 

--CREATE TABLE FOR GENRES : 
 DROP TABLE GENRES
/
CREATE TABLE GENRES ( ID NUMBER(5) , NAME VARCHAR2(50)); 

--CREATE TABLE FOR MOVIES 
DROP TABLE MOVIES
/
CREATE TABLE MOVIES ( ID NUMBER(5), TITLE VARCHAR2(50), RELEASE_DATE INT, DURATIONTIME INT , SCORE NUMBER(2,1) );

--CREATE AN ASSOCIATION TABLE 
DROP TABLE ASOCIERE 
/
CREATE TABLE ASOCIERE ( ID_MOVIE NUMBER(5), ID_GENDER NUMBER(5) );

