                                                          LABORATORUL 8 - JAVA  - WORKING WITH DATABASE 

DROP TABLE GENRES
/
CREATE TABLE GENRES ( ID NUMBER(5) , NAME VARCHAR2(50)); 


DROP TABLE MOVIES
/
CREATE TABLE MOVIES ( ID NUMBER(5), TITLE VARCHAR2(50), RELEASE_DATE INT, DURATIONTIME INT , SCORE NUMBER(2,1) );


DROP TABLE ASOCIERE 
/
CREATE TABLE ASOCIERE ( ID_MOVIE NUMBER(5), ID_GENDER NUMBER(5) );


DROP TABLE DIRECTORS
/
CREATE TABLE DIRECTORS ( ID NUMBER(5), NAME VARCHAR2(50), COUNTRY VARCHAR2(50), DURATIONTIME INT , MOVIE VARCHAR2(50) );


DROP TABLE ACTORS
/
CREATE TABLE ACTORS ( ID NUMBER(5) PRIMARY KEY, NAME VARCHAR2(50), COUNTRY VARCHAR2(50));

DROP SEQUENCE artistSequence;
/
CREATE SEQUENCE artistSequence START WITH 1;




---make a sequence for movie
DROP SEQUENCE idMovie;
/
CREATE SEQUENCE idMovie START WITH 1;

SELECT *FROM ACTORS;


--- MAKE A TRIGGER FOR MOVIE 
--
--create or replace TRIGGER idMovieTrigger 
--BEFORE INSERT ON MOVIES
--FOR EACH ROW
--BEGIN
--  IF :new.id is null then
--  SELECT idMovie.NEXTVAL INTO :new.id FROM DUAL;
--  END IF;
--END;
